[package]
name = "ncurses"
version = "5.82.0"
authors = [ "contact@jeaye.com" ]
description = "A very thin wrapper around the ncurses TUI library"
documentation = "https://github.com/jeaye/ncurses-rs"
homepage = "https://github.com/jeaye/ncurses-rs"
repository = "https://github.com/jeaye/ncurses-rs"
readme = "README.md"
keywords = ["ncurses","TUI"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2"

[features]
default=[]
wide = []
panel = []
menu = []

[lib]
name = "ncurses"
